### ISSUE TITLE
Question: Can I use keyvault-certificate-rotation on Azure Application Gateway?

### ISSUE THREAD

**Issue by soderlind** [shibayan/keyvault-certificate-rotation#12]
The subject say it all, can I use keyvault-certificate-rotation on Azure Application Gateway?

**Comment by shibayan** [comment]
Application Gateway supports automatic renewal of certificates, according to the documentation, so it is not necessary.

>The instances also poll Key Vault at 4-hour intervals to retrieve a renewed version of the certificate, if it exists. If an updated certificate is found, the TLS/SSL certificate currently associated with the HTTPS listener is automatically rotated.

https://docs.microsoft.com/en-us/azure/application-gateway/key-vault-certs

**Comment by soderlind** [comment]
@shibayan, thank you for your swift answer.
