### ISSUE TITLE
Specification in documentation

### ISSUE THREAD

**Issue by Woap** [shibayan/keyvault-certificate-rotation#2]
Hi, 

Firstly thanks for this useful function.

Having a question concerning the usage of this function. Shouldn't we specify the Vault and CDN / CDN Endpoint on which it has to do the rotation ? Does the function detect it automatically ? 

I didn't see any parameter in the function concerning those resources.

**Comment by shibayan** [comment]
It is not necessary to specify the CDN name or Front Door name because it automatically recognizes the CDN Profile / Endpoint / Front Door that has been permitted access by RBAC.

However, only the CDN / Front Door that exists in the same subscription as the Function are included.

**Comment by Woap** [comment]
Thank you, that's all I wanted to know
